# model
model_name_or_path: 'llama-65B'
#cache_dir: '/remote-home/share/llama'
# data
dataset_name: 'belle'
data_path:
  train: 'BelleGroup/train_2M_CN'
  eval: 'examples/belle/eval/eval_set.json'
  test: 'examples/belle/eval/eval_set.json'
data_cache_dir: 'cache'
refresh: false
data_tag: 'chinese'
train_on_inputs: true
max_length: 1024
sample_size: 10000
#special_tag: '（我能行）'
#training
tag: 'sft-1w-eval-debug'
output_dir: 'temp'
overwrite_output_dir: true
do_train: false
do_eval: true
evaluation_strategy: 'no'
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 0.03
weight_decay: 0
num_train_epochs: 30
lr_scheduler_type: 'constant'
warmup: 0.05
clip_grad_norm: 5.0
#clip_grad_value: 1.0
#clip_loss_value: 5.0
log_level: 'info'
logging_steps: 1
resume_from_checkpoint: 'outputs/belle_llama-65B_sft-1w/output_constant_warmup0.05_clipgradnorm5.0/checkpoint-0'
save_strategy: 'no'
save_total_limit: 0
seed: 42
fp16: true
remove_unused_columns: false
load_best_model_at_end: false
metric_for_best_model: 'score'
optim: 'sgd'
#group_by_length: true
report_to: 'wandb'
dataloader_pin_memory: false
gradient_checkpointing: false
#length_normalization: false
#unconditional_normalization: true
#generate
max_new_tokens: 1024
temperature: 1.0
#top_k: 30
top_p: 0.2
#repetition_penalty: 1.2
#do_sample: true