# model
model_name_or_path: '/remote-home/share/llama_hf/65B'
# data
dataset_name: 'openbookqa'
refresh: false
data_tag: 'src'
max_length: 256
# collie
# trainer
tag: 'test'
output_dir: 'outputs'
overwrite_output_dir: true
deepspeed: 'ds_config.json'
do_train: true
do_eval: false
evaluation_strategy: 'no'
per_device_train_batch_size: 4
per_device_eval_batch_size: 8
learning_rate: 0.005
weight_decay: 0
num_train_epochs: 10
lr_scheduler_type: 'linear'
warmup: 0.05
clip_grad_value: 1.0
#clip_loss_value: 5.0
log_level: 'info'
logging_steps: 1
save_strategy: 'no'
save_total_limit: 0
seed: 42
bf16: true
remove_unused_columns: false
load_best_model_at_end: false
metric_for_best_model: 'acc'
optim: 'sgd'
group_by_length: false
#report_to: 'wandb'
dataloader_pin_memory: false
gradient_checkpointing: true
predict_with_generate: true