# model
model_name_or_path: '/home/ubuntu/projects/collie/cache/llama-65b'
cache_dir: '/home/ubuntu/projects/collie/cache'
# data
dataset_name: 'openbookqa'
refresh: false
data_tag: 'src'
max_length: 256
# collie
# trainer
tag: 'test'
output_dir: 'outputs'
overwrite_output_dir: true
deepspeed: 'ds_config_v100.json'
do_train: true
do_eval: false
evaluation_strategy: 'epoch'
per_device_train_batch_size: 8
per_device_eval_batch_size: 2
learning_rate: 0.02
weight_decay: 0
num_train_epochs: 20
lr_scheduler_type: 'constant'
warmup: 0.025
clip_grad_value: 1.0
#clip_loss_value: 5.0
log_level: 'info'
logging_steps: 1
save_strategy: 'no'
save_total_limit: 0
seed: 42
remove_unused_columns: false
load_best_model_at_end: false
metric_for_best_model: 'acc'
optim: 'sgd'
group_by_length: false
#report_to: 'wandb'
dataloader_pin_memory: false
gradient_checkpointing: true
predict_with_generate: true